name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
              
      - name: Build with Gradle
        run: cd CancerPatients && ./gradlew build --no-daemon
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: cd
        run: cd /home/runner/work/LungCancerPatients/LungCancerPatients
      
      - name: pwd
        run: pwd

      - name: ls
        run: ls
        
      - name: Upload to AWS S3
        run: aws s3 cp --recursive --region ap-northeast-2 build s3://lung-cancer-patients.com

